/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToolbar: typeof import('./src/components/AppToolbar.vue')['default']
    Auth: typeof import('./src/components/Auth.vue')['default']
    GoogleLoginComponent: typeof import('./src/components/GoogleLoginComponent.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    ProjecT: typeof import('./src/components/ProjecT.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingUpForm: typeof import('./src/components/SingUpForm.vue')['default']
  }
}
